<a href="https://colab.research.google.com/github/Anamika-Suresh/numpy-exercise/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import numpy as np and see the version

In [2]:
import numpy as np

### Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [3]:
arr = np.array(range(1,11)).reshape(2,5)

In [4]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [ ]:
arr = np.array(range(1,21))
print(arr[5:16])  #based on index number a[5]

[ 6  7  8  9 10 11 12 13 14 15 16]


### How to compute the mean, median, standard deviation of a numpy array?Use the array you created above

In [ ]:
print(np.mean(arr))

10.5


In [ ]:
print(np.median(arr))

10.5


In [ ]:
print(np.std(arr))

5.766281297335398


In [ ]:
print(np.var(arr))

33.25


### Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of shape (4,). Subtract y from each row of x using broadcasting.

In [ ]:
x = np.array([[5, 10, 15, 20],
              [25, 30, 35, 40],
              [45, 50, 55, 60]])
y = y = np.array([1, 2, 3, 4])
print(x-y)

[[ 4  8 12 16]
 [24 28 32 36]
 [44 48 52 56]]
